# Generated by Django 3.2.9 on 2021-11-09 22:40

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotes', models.IntegerField()),
                ('price', models.FloatField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('paid', 'Paid'), ('canceled', 'Canceled'), ('finished', 'Finished')], max_length=50)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='game.option')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuoteManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_quotes', models.IntegerField(blank=True, default=250)),
                ('quotes_sold', models.IntegerField(validators=[django.core.validators.MaxValueValidator(models.IntegerField(blank=True, default=250)), django.core.validators.MinValueValidator(0)])),
                ('price_quote', models.FloatField()),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='game.option')),
                ('requests', models.ManyToManyField(related_name='request_quotes', to='lottery.Request')),
            ],
        ),
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
                ('prize', models.FloatField()),
                ('numbers_drawn', models.CharField(max_length=250)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='game.game')),
            ],
        ),
    ]
