# Generated by Django 3.2.9 on 2021-11-09 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numbers', models.CharField(max_length=250)),
                ('proof', models.ImageField(upload_to='')),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('contest', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='lottery.contest')),
            ],
        ),
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_prize', models.FloatField()),
                ('winning_numbers', models.IntegerField()),
                ('bet', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='lottery.bet')),
            ],
        ),
        migrations.AddField(
            model_name='bet',
            name='ticket',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='lottery.ticket'),
        ),
        migrations.AddField(
            model_name='quotemanager',
            name='ticket',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='lottery.ticket'),
            preserve_default=False,
        ),
    ]
