# Generated by Django 3.2.9 on 2021-11-10 00:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0003_auto_20211109_2104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prize',
            old_name='total_prize',
            new_name='prize',
        ),
        migrations.RemoveField(
            model_name='prize',
            name='winning_numbers',
        ),
        migrations.AddField(
            model_name='bet',
            name='win_prize',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prize',
            name='request',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='lottery.request'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quotemanager',
            name='quotes_sold',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(250), django.core.validators.MinValueValidator(0)]),
        ),
    ]
