# Generated by Django 3.2.9 on 2021-11-10 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0004_auto_20211109_2122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotemanager',
            name='max_quotes',
        ),
        migrations.AddField(
            model_name='quotemanager',
            name='open',
            field=models.BooleanField(default=True),
        ),
    ]
