# Generated by Django 3.2.9 on 2021-11-10 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0005_auto_20211109_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('finished', 'Finished')], default='open', max_length=50),
        ),
        migrations.AlterField(
            model_name='quotemanager',
            name='price_quote',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(default='open', max_length=50),
        ),
    ]
