# Generated by Django 3.2.9 on 2021-11-10 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_option_chance'),
        ('lottery', '0006_auto_20211110_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('finished', 'Finished')], default='open', max_length=50),
        ),
        migrations.AlterField(
            model_name='prize',
            name='bet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lottery.bet'),
        ),
        migrations.AlterField(
            model_name='quotemanager',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.option'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='contest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lottery.contest'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(default='open', max_length=50),
        ),
    ]
