# Generated by Django 3.2.9 on 2021-11-10 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0008_auto_20211110_0744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotemanager',
            name='open',
        ),
        migrations.RemoveField(
            model_name='quotemanager',
            name='price_quote',
        ),
        migrations.RemoveField(
            model_name='quotemanager',
            name='requests',
        ),
        migrations.AddField(
            model_name='quotemanager',
            name='request',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, to='lottery.request'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='requests',
            field=models.ManyToManyField(through='lottery.QuoteManager', to='lottery.Request'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('finished', 'Finished')], default='open', max_length=50),
        ),
        migrations.AlterField(
            model_name='quotemanager',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lottery.ticket'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(default='open', max_length=50),
        ),
    ]
