# Generated by Django 3.2.9 on 2021-11-10 12:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0009_auto_20211110_0946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotemanager',
            name='quotes_sold',
        ),
        migrations.AddField(
            model_name='ticket',
            name='quotes_sold',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(250), django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contest',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('finished', 'Finished')], default='open', max_length=50),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(default='open', max_length=50),
        ),
    ]
