# Generated by Django 3.2.9 on 2021-11-10 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_option_chance'),
        ('lottery', '0010_auto_20211110_0955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotemanager',
            name='option',
        ),
        migrations.AddField(
            model_name='ticket',
            name='option',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='game.option'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contest',
            name='prize',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='contest',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('finished', 'Finished')], default='open', max_length=50),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(default='open', max_length=50),
        ),
    ]
