# Generated by Django 3.2.9 on 2021-11-10 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0012_auto_20211110_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='prize',
            name='winners',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bet',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('no_prize', 'No Prize'), ('with_prize', 'With Prize')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='contest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('finished', 'Finished')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(default='open', max_length=50),
        ),
    ]
