# Generated by Django 3.2.9 on 2021-12-24 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercontact',
            name='user',
        ),
        migrations.AddField(
            model_name='userdocs',
            name='phone',
            field=models.CharField(default=9999999999, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userfinanceinfo',
            name='balance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userfinanceinfo',
            name='pix_key',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='UserBalance',
        ),
        migrations.DeleteModel(
            name='UserContact',
        ),
    ]
