# Generated by Django 3.2.9 on 2021-11-09 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_game_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='chance',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
