# Generated by Django 3.2.9 on 2021-11-11 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_option_chance'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='quote_value',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='option',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='game.game'),
        ),
    ]
