# Generated by Django 3.2.9 on 2021-11-22 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20211110_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='queue_numbers',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='total_numbers',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
