# Generated by Django 3.2.9 on 2021-11-22 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20211122_1507'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='queue_numbers',
            new_name='total_queues',
        ),
    ]
