export const URL = 'http://127.0.0.1:8000/'
export const endpoint_games = 'api/games/'
export const endpoint_send_request = 'api/profile/request/'
export const endpoint_cart = 'api/profile/cart/'
export const endpoint_quote_manager = 'api/profile/quote_manager/'
export const endpoint_bet = 'api/profile/bets/'