from django.urls import path
from .views import (Cart, CartLength, GamesView, QuoteManagerView,
                    RequestView,
                    BetView,
                    ContestView,
                    TicketView)
urlpatterns = [
    path('games/', 
        GamesView.as_view({
            'get':'list'
        })),
    path('games/<int:pk>', 
        GamesView.as_view({
            'get':'retrieve'
        })),
    path('contest/', 
        ContestView.as_view({
            'get':'list'
        })),
    path('contest/<int:pk>', 
        ContestView.as_view({
            'get':'retrieve'
        })),
    path('profile/request/', 
        RequestView.as_view({
            'post':'create',    
            'get':'list'
        })),
    path('profile/request/<int:pk>',
        RequestView.as_view({
            'get':'retrieve'
    })),
    path('profile/bets/',
        BetView.as_view({
            'get':'list'
        })),
    path('profile/bets/<int:pk>/',
        BetView.as_view({
            'get':'retrieve'
        })),
    path('profile/tickets/',
        TicketView.as_view({
            'get':'list'
        })),
    path('profile/tickets/<int:pk>/',
        TicketView.as_view({
            'get':'retrieve'
        })),
    path('profile/cart/',
        Cart.as_view({
            'get':'list',
            'post':'pay'
        })),
    path('profile/cart/<int:pk>/',
        Cart.as_view({
            'delete':'destroy'
        })),
    path('profile/cart/length/',
        CartLength.as_view()),
    path('profile/quote_manager/',
        QuoteManagerView.as_view()),
]
